<?php

namespace Database\Seeders;

use App\Models\ModelOfBrand;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ModelOfBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ModelOfBrand::insert([
            [
                'brand_id' => 1,
                'name' => 'Alto',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Astra',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Bel Air',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Camaro',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Aveo',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Cavalier',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Celebrity',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Citation',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Corsa',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Chevy',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Epica',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Esteem',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Impala',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Malibu',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Monza',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Optra',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Spark',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Sprint',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Style',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Line',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Swift',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Wagon R+',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Sail',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Buick',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Cruze',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => '39',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Cobalt',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Sonic',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Onix',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Beat',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Vivant',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Blazer 4x2',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Captiva',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Tahoe',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'HHR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Courier',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Zafira',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Blazer',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => '4x4',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Grand',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Vitara',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Grand Blazer',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Rodeo',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Suburban',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Trail',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Blazer',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Traverse',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Orlando',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Tracker',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Equinox',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Jimny',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Samurai',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Trooper',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Vitara',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FSR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FVR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FTR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NNR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Cheyenne',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'C30',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => '3100',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Brigadier',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'C70',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Carry',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NHR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NPR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NKR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Super',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Brigadier',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Super',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Carry',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Kodiak',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NQR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FRR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FVZ',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'N300',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'D-max',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'DMAX',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Super',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Carry',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NQR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'FRR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Carry',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'CHR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'LV',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NKR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'NPR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'D-max',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'SSR',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv Dmax',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'N300',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Apache',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'C10',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'C30',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Cheyenne',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv 1.6',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv 2.2',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv 2.3',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv 2.5',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Colorado',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Luv 2.8',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Silverado',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Optra',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Spark',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Corsa',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Taxi',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Chevette',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Chevytaxi',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => '7:24',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'ChevyVan',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'ChevyWagon',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Super',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'Carry',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'N200',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'name' => 'N300',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Fusion',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Crown',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Victoria',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Falcon',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Festiva',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Fiesta',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Focus',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Granada',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Laser',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Mustang',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Taurus',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Hot',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Rod',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Escort',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Ltd',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => '555E',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Chiva',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Ecosport',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Panel',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Edge',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Flex',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Courier',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Escape',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Expedition',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Explorer',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Llanero',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Bronco',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Piragua',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Aeromax',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Cargo',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => '815',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F350',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => '600',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F8000',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F 600',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F 350[7]',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F9000',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F-150',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Cargo 1019',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Cargo 816',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F250',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Nueva',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Ranger',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Explorer',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F100',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F-150',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'F350',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'name' => 'Ranger',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now(),
            ],
        ]);
    }
}
